import Head from "next/head";
import styles from "../styles/Home.module.css";
import Snippets from "../components/Snippets";
import useSWR from "swr";
import Link from 'next/link';
import { signIn, signOut, useSession } from "next-auth/client";

export default function Home() {
  const { data: snippets, mutate } = useSWR(
    "/api/snippets"
  );
  const [session, loadingSession] = useSession();
  if (loadingSession) {
    <>
      <p>...authenticating</p>
    </>;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>View Snippet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {!session && (
        <>
          <h1>Sign in to access snippet app</h1>
          <button onClick={() => signIn()}>Sign In</button>
        </>
      )}
      {session && (
        <>
          <main className={styles.main}>
            <h3>welcome {session.user.email}</h3>
            <button onClick={() => signOut()}>Sign Out</button>
            <h1 className={styles.title}>Re-usuable Code Snippets</h1>
            <p className={styles.info}>Add your code snippets here...</p>
            <Link href="/upload">
              <button>Create new snippet</button>
            </Link>
            {snippets &&
              snippets.map((snippet) => (
                <Snippets
                  key={snippet.id}
                  snippet={snippet}
                  snippetDeleted={mutate}
                  email={session.user.email}
                />
              ))}
          </main>
        </>
      )}
    </div>
  );
}
